version: "3.9"
services:
  iconduct:
    image: ${DOCKER_REGISTRY-}iconduct
    build:
      context: .
      dockerfile: IConduct/Dockerfile 
    ports:
      - "5000:80" 
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User=sa;Password=Some!Conduct1Password;
    depends_on:
      - db 
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: sql_server
    ports:
      - "1433:1433" 
    environment:
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: "Some!Conduct1Password"
    volumes:
      - mssql_data:/var/opt/mssql 
    restart: always 

volumes:
  mssql_data: 
